version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Ubuntu2004
configuration: Release
only_commits:
  files:
    - Wrapr/**/*
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build:
  publish_nuget: true
  verbosity: minimal
before_test:
  - sudo wget -q https://raw.githubusercontent.com/dapr/cli/master/install/install.sh -O - | /bin/bash
  - dapr init --slim
after_test:
  - dotnet tool restore && cd Wrapr.Tests && dotnet dotnet-stryker
test_script:
  - dotnet test --collect:"XPlat Code Coverage"
environment:
  DOCKER_TOKEN:
    secure: Dj3j/X71ZSCnXP24pR/1fmGLBKUYFOeN7R9s+QioevmuSGjGzAGq19hIws1w4Csa
for:
  -
    branches:
      only:
        - main
        - stryker
    environment:
      CODECOV_TOKEN: c55b0da7-51ca-4c36-9504-0b118e9dc8e1
      STRYKER_DASHBOARD_API_KEY:
        secure: qJ2eTguSaMRR/xgLMgHV+eN8wLHLxMyyAo0sbUdt+JkYmHR2LDntlettI/YJDT7n
    after_test:
      - bash <(curl -s https://codecov.io/bash)
      - dotnet tool restore && cd Wrapr.Tests && dotnet dotnet-stryker --reporters "['dashboard']" --dashboard-api-key $STRYKER_DASHBOARD_API_KEY --dashboard-project github.com/riezebosch/Dapr.Wrapr/main
    deploy:
      - provider: NuGet
        api_key:
          secure: 6sPnG9susETMj+SCJB7ESTUOoqhVZ6OAO1W+Qb3Y0h+qjCOo5qnbev8l5ISg32hr
        on:
          branch: main